/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdultosRouteImport } from './routes/adultos'
import { Route as ConteudosRouteImport } from './routes/conteudos'
import { Route as InfantilRouteImport } from './routes/infantil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdultosRoute = AdultosRouteImport.update({
  id: '/adultos',
  path: '/adultos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRoute = ConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const InfantilRoute = InfantilRouteImport.update({
  id: '/infantil',
  path: '/infantil',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adultos': typeof AdultosRoute
  '/conteudos': typeof ConteudosRoute
  '/infantil': typeof InfantilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adultos': typeof AdultosRoute
  '/conteudos': typeof ConteudosRoute
  '/infantil': typeof InfantilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adultos': typeof AdultosRoute
  '/conteudos': typeof ConteudosRoute
  '/infantil': typeof InfantilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adultos' | '/conteudos' | '/infantil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adultos' | '/conteudos' | '/infantil'
  id: '__root__' | '/' | '/adultos' | '/conteudos' | '/infantil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdultosRoute: typeof AdultosRoute
  ConteudosRoute: typeof ConteudosRoute
  InfantilRoute: typeof InfantilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adultos': {
      id: '/adultos'
      path: '/adultos'
      fullPath: '/adultos'
      preLoaderRoute: typeof AdultosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos': {
      id: '/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof ConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infantil': {
      id: '/infantil'
      path: '/infantil'
      fullPath: '/infantil'
      preLoaderRoute: typeof InfantilRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdultosRoute: AdultosRoute,
  ConteudosRoute: ConteudosRoute,
  InfantilRoute: InfantilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
